language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_script:
  - npm install
before_deploy:
  - npm pack
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "it-quasar-01cat-deploy-*.tgz"
    skip_cleanup: true
    on:
      tags: true
