language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - node_modules/.bin/tsc
before_deploy:
  - npm pack
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "it-quasar-01cat-deploy-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    api_key: $NPM_TOKEN
    email: "0x6368656174@gmail.com"
    skip_cleanup: true
    on:
      tags: true
