language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
before_script:
- npm install
before_deploy:
- npm pack
deploy:
  provider: releases
  api_key:
    secure: Q4svr9CvqccuLFFLiV6AqYKFgPFJROySTF7+y15pbc6wktvP+OmKI8PtzYjOeDQq+rxFBLzOksPsdBcrfnSWEiM4xTDXIZodNfTiSEoZagvvDqIGfLJ27JeXzv8uw5bqWr8qYoH3PWwxe/1/zwpSM/u29gom/VFnM4g2Cj81jflLYNkdFMYK2JvAK+u7Umgy8BJaGZzYGsA+/iWZwOIsWhpY+7OdpYv9s7U2spLZaq+nIg87iQSdN5pV0g0zwV6OqArWJAaTEeMd1RmfuzQg90rsMUNspL0dbLSB6wwzls4vU4jMJI5j5Z2lErhI7nlBf3sz+PwrOBdxCMPucA3QKVA9+DBmxm4qSgPn+Um7bh9xmnSoWWYo/ifBzScAM/DzMaynmthHhQ9twe0N/P07+YsKJdEXW4xxjUpQU8BoAJjTK7Ciq+ICGFHp/JzqrJ49Y1Sig7J8Wg0Ph1NA7R+aNzuCFgy+uyjVnNrg0hJr3KstejWQZ/SIDFYE+O8D+Vlnju48amfeuLDIF7tkLCzj2TUEqAAwJqMVxzYxc+hvPSfq2dk0gUvhoMCNXxwGt+PpEd3XwMulhjaGZJGlM7V5rTFZsTJdlmC50e8p5sHn09mM0kCOFtGMvk7sryfrkGRrNuFIoMFlYX33R4MxnVcW+Fkjx4JthM15Hjro6jl7N7Q=
  file: it-quasar-01cat-deploy-*.tgz
  on:
    tags: true
    repo: it-quasar/01cat-deploy
